# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
                ('published', models.DateField(null=True, verbose_name='Date Published')),
                ('content', models.TextField(help_text='Use Markdown syntax.', verbose_name='Page body')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
