# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20161108_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_type',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('markdown', 'Markdown'), ('table', 'Table'), ('gallery', 'Gallery')], default='markdown', max_length=10),
        ),
    ]
